file(REMOVE ${TEST_FILE})
execute_process(COMMAND ${TEST_COMMAND}
    INPUT_FILE ${TEST_INPUT}
)
FILE(READ ${TEST_FILE} TEST_FILE_CONTENTS)
STRING(FIND "${TEST_FILE_CONTENTS}" "FATAL" CONTAINS_FATAL)
IF(NOT (${CONTAINS_FATAL} EQUAL -1))
    MESSAGE(FATAL_ERROR "Error")
ENDIF()