ifeq ($(CORE), C910V)
# Upstream GCC 14+ rejects the Xuantie march string and -mtune=c920.
# It spells T-Head vector as xtheadvector and requires a th. prefix in
# the C910 GEMM kernels (see kernel/riscv64/c910v_asm.h).
C910V_UPSTREAM_GCC := $(shell printf '%s\n' 'int c910v_probe;' | $(CC) -march=rv64gc_xtheadvector -mabi=lp64d -x c -c -o /dev/null - >/dev/null 2>&1 && echo 1)
ifeq ($(C910V_UPSTREAM_GCC), 1)
CCOMMON_OPT += -march=rv64gc_xtheadvector -mabi=lp64d
FCOMMON_OPT += -march=rv64gc_xtheadvector -mabi=lp64d -static
else
CCOMMON_OPT += -march=rv64imafdcv0p7_zfh_xtheadc -mabi=lp64d -mtune=c920
FCOMMON_OPT += -march=rv64imafdcv0p7_zfh_xtheadc -mabi=lp64d -mtune=c920 -static
endif
endif
ifeq ($(CORE), x280)
CCOMMON_OPT += -march=rv64imafdcv_zba_zbb_zfh_zvl512b -mabi=lp64d 
FCOMMON_OPT += -march=rv64imafdcv_zba_zbb_zfh -mabi=lp64d -static
endif
RISCV64_OPT  = rv64imafdcv
ifeq ($(BUILD_HFLOAT16), 1)
RISCV64_OPT := $(RISCV64_OPT)_zvfh_zfh
endif
ifeq ($(BUILD_BFLOAT16), 1)
RISCV64_OPT := $(RISCV64_OPT)_zvfbfwma
endif
ifeq ($(CORE), RISCV64_ZVL256B)
CCOMMON_OPT += -march=$(RISCV64_OPT)_zvl256b -mabi=lp64d
FCOMMON_OPT += -march=$(RISCV64_OPT) -mabi=lp64d
endif
ifeq ($(CORE), RISCV64_ZVL128B)
CCOMMON_OPT += -march=$(RISCV64_OPT) -mabi=lp64d
FCOMMON_OPT += -march=$(RISCV64_OPT) -mabi=lp64d
endif
ifeq ($(CORE), RISCV64_GENERIC)
CCOMMON_OPT += -march=rv64imafdc -mabi=lp64d
FCOMMON_OPT += -march=rv64imafdc -mabi=lp64d
endif
ifeq ($(CORE), U74)
CCOMMON_OPT += -march=rv64imafdc_zba_zbb -mabi=lp64d -mtune=sifive-u74
FCOMMON_OPT += -march=rv64imafdc_zba_zbb -mabi=lp64d -mtune=sifive-u74
endif
