ifeq ($(CORE), LOONGSON3R5)
CCOMMON_OPT += -march=loongarch64
FCOMMON_OPT += -march=loongarch64

ifeq ($(LOONGARCH_CC_FLAVOR), NEW)
CCOMMON_OPT += -mabi=lp64d
FCOMMON_OPT += -mabi=lp64d
endif
ifeq ($(LOONGARCH_CC_FLAVOR), OLD)
CCOMMON_OPT += -mabi=lp64
FCOMMON_OPT += -mabi=lp64
endif
endif
