/*****************************************************************************
 * Shared infrastructure for the dedicated high-level LAPACKE tests.
 *
 * Each test lives in its own source file high_level/<x><routine>.c and
 * defines one test function via the LAPACKE_TEST macro:
 *
 *     #include "lapacke_test.h"
 *
 *     LAPACKE_TEST(dgels)
 *     {
 *         ...calls to lapacke_test_check(...)...
 *     }
 *
 * There is one runner per precision; their test tables are generated by
 * CMake from the routine names in LAPACKE/testing/high_level/CMakeLists.txt.
 * The file name (without extension) must match the name used in the
 * LAPACKE_TEST macro, otherwise the link fails.
 *
 * The implementation is split by topic: check reporting in lapacke_test.c,
 * allocation tracking and failure injection in lapacke_test_alloc.c, test
 * matrix generation in lapacke_test_matgen_<x>.c, and the NaN position
 * sweeps in lapacke_test_nan_sweep.c.
 *****************************************************************************/

#ifndef LAPACKE_TEST_H
#define LAPACKE_TEST_H

#include <stddef.h>

#include "lapacke.h"

#define API_SUFFIX(x) x

/** Defines the test function collected by the generated test runner. */
#define LAPACKE_TEST(name) void lapacke_test_fn_##name(void)

/* Dimensions of the shared test matrices. Rectangular (M > N) where the
 * routine allows it; LD leaves padding beyond the matrix in both layouts.
 * Buffers of LAPACKE_TEST_LD * LAPACKE_TEST_LD doubles fit every layout. */

/** Row count of the shared test matrices. */
#define LAPACKE_TEST_M 4
/** Column count of the shared test matrices. */
#define LAPACKE_TEST_N 3
/** Number of right-hand sides in the shared test matrices. */
#define LAPACKE_TEST_NRHS 2
/** Leading dimension of the shared test matrix buffers. */
#define LAPACKE_TEST_LD 5

/** A matrix_layout value that is neither LAPACK_COL_MAJOR nor
 *  LAPACK_ROW_MAJOR, for the invalid-layout error tests. */
#define LAPACKE_TEST_INVALID_LAYOUT 0

/** Global count of checks run, reported by the test runner. */
extern int lapacke_test_checks;
/** Global count of failed checks, reported by the test runner. */
extern int lapacke_test_failures;

/** Both matrix layouts (indices 0 and 1), for layout loops, plus
 *  LAPACKE_TEST_INVALID_LAYOUT (index 2) for the argument-error tests. */
extern const int lapacke_test_layouts[3];
/** Printable names matching lapacke_test_layouts. */
extern const char *lapacke_test_layout_names[3];

/** A quiet NaN produced at run time (not folded by the compiler). */
double lapacke_create_nan(void);

/** A quiet NaN, single precision real. */
float lapacke_test_snan(void);
/** A quiet NaN, double precision real. */
double lapacke_test_dnan(void);
/** A quiet NaN in both parts, single precision complex. */
lapack_complex_float lapacke_test_cnan(void);
/** A quiet NaN in both parts, double precision complex. */
lapack_complex_double lapacke_test_znan(void);

/** Record one check of an info result against its expected value. */
void lapacke_test_check(const char *name, const char *variant, lapack_int info,
                        lapack_int expected);

/* ------------------------------------------------------------------------
 * Allocation failure injection and leak tracking (lapacke_test_alloc.c).
 * ---------------------------------------------------------------------- */

/** The counting/failing test allocator. */
void *lapacke_test_malloc(size_t size);

/** The deallocator matching lapacke_test_malloc. */
void lapacke_test_free(void *ptr);

/** Schedule the (countdown+1)-th LAPACKE allocation to fail once. */
void lapacke_test_schedule_malloc_failure(long countdown);

/** Record one check that a call consumed the scheduled countdown exactly. */
void lapacke_test_check_alloc_count(const char *name);

/** Record one check that every tracked allocation has been freed. */
void lapacke_test_check_leaks(const char *name);

/* ------------------------------------------------------------------------
 * Test matrix generation (lapacke_test_matgen_<x>.c, one per precision).
 *
 * One fill per conventional-storage matrix type: the fill functions write
 * the whole allocated buffer (including padding). The random matrices are
 * generated with ?LATMS (well conditioned) using a fixed seed per fill
 * type, so repeated calls produce identical data; the _nan fills flood the
 * buffer with NaNs instead. Band and packed storage have their own buffer
 * geometry and get their fills with the routines that first need them.
 *
 * The complex fills generate Hermitian matrices where the real ones
 * generate symmetric matrices, matching what the complex routines read.
 * ---------------------------------------------------------------------- */

/** Fill a with a random general rows-by-cols matrix, single precision. */
void lapacke_test_sfill(int layout, lapack_int rows, lapack_int cols, float *a,
                        lapack_int ld);
/** Fill a with a random symmetric positive definite n-by-n matrix, single
 *  precision. */
void lapacke_test_sfill_spd(int layout, lapack_int n, float *a, lapack_int ld);
/** Fill a with a random symmetric indefinite n-by-n matrix, single
 *  precision. */
void lapacke_test_sfill_sym(int layout, lapack_int n, float *a, lapack_int ld);
/** Fill a with a random nonsingular triangular n-by-n matrix, single
 *  precision. */
void lapacke_test_sfill_tri(int layout, char uplo, lapack_int n, float *a,
                            lapack_int ld);
/** Fill b with a random right-hand side, single precision. */
void lapacke_test_sfill_rhs(int layout, lapack_int rows, lapack_int cols,
                            float *b, lapack_int ld);
/** Fill every allocated position of a matrix buffer with NaN, single
 *  precision. */
void lapacke_test_sfill_nan(int layout, lapack_int rows, lapack_int cols,
                            float *a, lapack_int ld);

/** Fill a with a random general rows-by-cols matrix, double precision. */
void lapacke_test_dfill(int layout, lapack_int rows, lapack_int cols, double *a,
                        lapack_int ld);
/** Fill a with a random symmetric positive definite n-by-n matrix, double
 *  precision. */
void lapacke_test_dfill_spd(int layout, lapack_int n, double *a, lapack_int ld);
/** Fill a with a random symmetric indefinite n-by-n matrix, double
 *  precision. */
void lapacke_test_dfill_sym(int layout, lapack_int n, double *a, lapack_int ld);
/** Fill a with a random nonsingular triangular n-by-n matrix, double
 *  precision. */
void lapacke_test_dfill_tri(int layout, char uplo, lapack_int n, double *a,
                            lapack_int ld);
/** Fill b with a random right-hand side, double precision. */
void lapacke_test_dfill_rhs(int layout, lapack_int rows, lapack_int cols,
                            double *b, lapack_int ld);
/** Fill every allocated position of a matrix buffer with NaN, double
 *  precision. */
void lapacke_test_dfill_nan(int layout, lapack_int rows, lapack_int cols,
                            double *a, lapack_int ld);

/** Fill a with a random general rows-by-cols matrix, single precision
 *  complex. */
void lapacke_test_cfill(int layout, lapack_int rows, lapack_int cols,
                        lapack_complex_float *a, lapack_int ld);
/** Fill a with a random Hermitian positive definite n-by-n matrix, single
 *  precision complex. */
void lapacke_test_cfill_spd(int layout, lapack_int n, lapack_complex_float *a,
                            lapack_int ld);
/** Fill a with a random Hermitian indefinite n-by-n matrix, single
 *  precision complex. */
void lapacke_test_cfill_sym(int layout, lapack_int n, lapack_complex_float *a,
                            lapack_int ld);
/** Fill a with a random nonsingular triangular n-by-n matrix, single
 *  precision complex. */
void lapacke_test_cfill_tri(int layout, char uplo, lapack_int n,
                            lapack_complex_float *a, lapack_int ld);
/** Fill b with a random right-hand side, single precision complex. */
void lapacke_test_cfill_rhs(int layout, lapack_int rows, lapack_int cols,
                            lapack_complex_float *b, lapack_int ld);
/** Fill every allocated position of a matrix buffer with NaN, single
 *  precision complex. */
void lapacke_test_cfill_nan(int layout, lapack_int rows, lapack_int cols,
                            lapack_complex_float *a, lapack_int ld);

/** Fill a with a random general rows-by-cols matrix, double precision
 *  complex. */
void lapacke_test_zfill(int layout, lapack_int rows, lapack_int cols,
                        lapack_complex_double *a, lapack_int ld);
/** Fill a with a random Hermitian positive definite n-by-n matrix, double
 *  precision complex. */
void lapacke_test_zfill_spd(int layout, lapack_int n, lapack_complex_double *a,
                            lapack_int ld);
/** Fill a with a random Hermitian indefinite n-by-n matrix, double
 *  precision complex. */
void lapacke_test_zfill_sym(int layout, lapack_int n, lapack_complex_double *a,
                            lapack_int ld);
/** Fill a with a random nonsingular triangular n-by-n matrix, double
 *  precision complex. */
void lapacke_test_zfill_tri(int layout, char uplo, lapack_int n,
                            lapack_complex_double *a, lapack_int ld);
/** Fill b with a random right-hand side, double precision complex. */
void lapacke_test_zfill_rhs(int layout, lapack_int rows, lapack_int cols,
                            lapack_complex_double *b, lapack_int ld);
/** Fill every allocated position of a matrix buffer with NaN, double
 *  precision complex. */
void lapacke_test_zfill_nan(int layout, lapack_int rows, lapack_int cols,
                            lapack_complex_double *a, lapack_int ld);

/* ------------------------------------------------------------------------
 * NaN position sweeps (lapacke_test_nan_sweep.c).
 *
 * A sweep places a NaN in every position of the allocated buffer of a
 * matrix argument, one by one, and verifies that positions inside the
 * documented access region report the documented error code while all
 * other positions (unreferenced triangles, leading-dimension padding) are
 * ignored by the routine.
 *
 * A region maps logical coordinates (i, j) to nonzero if the routine reads
 * that element. The macros below cover the conventional-storage types;
 * routine-specific regions can be defined (as function-like macros or
 * functions) next to the test that needs them.
 * ---------------------------------------------------------------------- */

/** Region of a full matrix: every element is read. */
#define lapacke_test_region_full(i, j) 1
/** Region of an upper triangular matrix: i <= j. */
#define lapacke_test_region_upper(i, j) ((i) <= (j))
/** Region of a lower triangular matrix: i >= j. */
#define lapacke_test_region_lower(i, j) ((i) >= (j))
/** Region of a unit-diagonal upper triangular matrix (the diagonal is not
 *  referenced): i < j. */
#define lapacke_test_region_strict_upper(i, j) ((i) < (j))
/** Region of a unit-diagonal lower triangular matrix (the diagonal is not
 *  referenced): i > j. */
#define lapacke_test_region_strict_lower(i, j) ((i) > (j))

/** Number of buffer positions a rows-by-cols matrix with leading dimension
 *  ld occupies in the given layout. */
size_t lapacke_test_alloc_len(int layout, lapack_int rows, lapack_int cols,
                              lapack_int ld);

/** Map a buffer position to logical matrix coordinates. */
int lapacke_test_map_position(int layout, lapack_int rows, lapack_int cols,
                              lapack_int ld, size_t p, lapack_int *i,
                              lapack_int *j);

/** Print the detail line for one misreported NaN sweep position. */
void lapacke_test_sweep_mismatch(const char *name, const char *variant,
                                 lapack_int i, lapack_int j, lapack_int info,
                                 lapack_int expected);
/** Record the one aggregated check of a finished NaN sweep. */
void lapacke_test_sweep_result(const char *name, const char *variant,
                               size_t positions, int mismatches);

/**
 * Run one NaN sweep over a matrix argument; counts as one check.
 *
 * Use the per-precision LAPACKE_TEST_[SDCZ]NAN_SWEEP wrappers below rather
 * than this macro: they supply the NaN of the matching element type.
 *
 * \param nan_fn       Function returning the NaN to plant, of mat's element
 *                     type.
 * \param name         Name of the sweep, printed on the report line.
 * \param layout_index Index into lapacke_test_layouts selecting the layout.
 * \param rows         Number of matrix rows.
 * \param cols         Number of matrix columns.
 * \param mat          Buffer of the matrix argument to sweep.
 * \param ld           Leading dimension of mat in the selected layout.
 * \param region       Region macro or function; NaNs inside it must yield
 *                     the info value expected, NaNs outside it must yield 0.
 * \param expected     Info value the routine must report for a NaN inside
 *                     the region.
 * \param reset_expr   Expression (use the comma operator to refill several
 *                     matrices) that restores all inputs of call_expr.
 * \param call_expr    Expression evaluating to the routine's info result.
 */
#define LAPACKE_TEST_NAN_SWEEP_IMPL(nan_fn, name, layout_index, rows, cols,    \
                                    mat, ld, region, expected, reset_expr,     \
                                    call_expr)                                 \
    do {                                                                       \
        const int lts_layout = lapacke_test_layouts[layout_index];             \
        const size_t lts_len = lapacke_test_alloc_len(lts_layout, rows, cols,  \
                                                      ld);                     \
        size_t lts_p;                                                          \
        int lts_bad = 0;                                                       \
        for (lts_p = 0; lts_p < lts_len; lts_p++) {                            \
            lapack_int lts_i, lts_j, lts_info, lts_want;                       \
            int lts_inside;                                                    \
            (void)(reset_expr);                                                \
            lts_inside = lapacke_test_map_position(lts_layout, rows, cols, ld, \
                                                   lts_p, &lts_i, &lts_j);     \
            (mat)[lts_p] = nan_fn();                                           \
            lts_info = (call_expr);                                            \
            lts_want = (lts_inside && region(lts_i, lts_j)) ? (expected) : 0;  \
            if (lts_info != lts_want) {                                        \
                lapacke_test_sweep_mismatch(                                   \
                    name, lapacke_test_layout_names[layout_index], lts_i,      \
                    lts_j, lts_info, lts_want);                                \
                lts_bad++;                                                     \
            }                                                                  \
        }                                                                      \
        lapacke_test_sweep_result(                                             \
            name, lapacke_test_layout_names[layout_index], lts_len, lts_bad);  \
    } while (0)

/* MSVC's legacy preprocessor substitutes __VA_ARGS__ as one single argument
 * when it is forwarded to a function-like macro. The extra rescan this
 * indirection forces splits it back into separate arguments; it is a no-op
 * for conforming preprocessors. */
#define LAPACKE_TEST_EXPAND(x) x

/** Run one NaN sweep over a single precision real matrix argument. */
#define LAPACKE_TEST_SNAN_SWEEP(...)                                           \
    LAPACKE_TEST_EXPAND(                                                       \
        LAPACKE_TEST_NAN_SWEEP_IMPL(lapacke_test_snan, __VA_ARGS__))
/** Run one NaN sweep over a double precision real matrix argument. */
#define LAPACKE_TEST_DNAN_SWEEP(...)                                           \
    LAPACKE_TEST_EXPAND(                                                       \
        LAPACKE_TEST_NAN_SWEEP_IMPL(lapacke_test_dnan, __VA_ARGS__))
/** Run one NaN sweep over a single precision complex matrix argument. */
#define LAPACKE_TEST_CNAN_SWEEP(...)                                           \
    LAPACKE_TEST_EXPAND(                                                       \
        LAPACKE_TEST_NAN_SWEEP_IMPL(lapacke_test_cnan, __VA_ARGS__))
/** Run one NaN sweep over a double precision complex matrix argument. */
#define LAPACKE_TEST_ZNAN_SWEEP(...)                                           \
    LAPACKE_TEST_EXPAND(                                                       \
        LAPACKE_TEST_NAN_SWEEP_IMPL(lapacke_test_znan, __VA_ARGS__))

#endif /* LAPACKE_TEST_H */
