name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Deploy docs
    if: "github.repository == 'OpenMathLib/OpenBLAS'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install MkDocs and doc theme packages
        run: pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin

      - name: Build docs site
        run: mkdocs build

      # mkdocs gh-deploy command only builds to the top-level, hence deploying
      # with this action instead.
      # Deploys to http://www.openmathlib.org/OpenBLAS/docs/
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        if: ${{ github.ref == 'refs/heads/develop' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          destination_dir: docs/
